spring:
  application:
    name: GeoService
  jmx:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5435/geo_db
    username: mike
    password: secret
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

server:
  port: 8083
