version: '3.8'
services:
  apigateway:
    build: ./APIGateway
    container_name: apigateway
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
    depends_on:
      authservice:
        condition: service_healthy
      restaurantservice:
        condition: service_healthy
      menuservice:
        condition: service_healthy
    networks:
      - appnet

  authservice:
    build: ./AuthService
    container_name: authservice
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: mike
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - appnet

  restaurantservice:
    build: ./RestaurantService
    container_name: restaurantservice
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-db:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: mike
      SPRING_DATASOURCE_PASSWORD: secret
      AUTH_SERVICE_URL: http://authservice:8081
      GEO_SERVICE_URL: http://geoservice:8083
    depends_on:
      restaurant-db:
        condition: service_healthy
      authservice:
        condition: service_healthy
      geoservice:
        condition: service_healthy
    networks:
      - appnet

  geoservice:
    build: ./GeoService
    container_name: geoservice
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://geo-db:5432/geo_db
      SPRING_DATASOURCE_USERNAME: mike
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      geo-db:
        condition: service_healthy
    networks:
      - appnet

  menuservice:
    build: ./MenuService
    container_name: menuservice
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://menu-db:5432/menu_db
      SPRING_DATASOURCE_USERNAME: mike
      SPRING_DATASOURCE_PASSWORD: secret
      RESTAURANT_SERVICE_URL: http://restaurantservice:8082
    depends_on:
      menu-db:
        condition: service_healthy
      restaurantservice:
        condition: service_healthy
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
