spring:
  application:
    name: APIGateway
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.web.servlet.function: DEBUG

jwt:
  secret: "1245789630ClickAndMunchSuperSecretKey1245789630"
  prefix: "Bearer "

server:
  port: 8080

